### ISSUE TITLE
403 on grpc@1.10.1 using npm

### ISSUE THREAD

**Issue by ThisIsSet-L** [nuxt-community/firebase-module#238]
Installing nuxt-firebase results in an npm error. The URL for the precompiled binaries results in a 403, and the source tarball isn't available.

```
[westj@twilightsparkle fillyradionuxt]$ npm i firebase nuxt-firebase btoa
npm WARN deprecated core-js@2.5.5: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> grpc@1.10.1 install /home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.1/node-v72-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.1 and node@12.16.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Pre-built binaries not installable for grpc@1.10.1 and node@12.16.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Hit error Connection closed while downloading tarball file 
make: Entering directory '/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
make: Entering directory '/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/build'
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
sed: can't read ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o.d.raw': No such file or directory
make: *** [grpc.target.mk:407: Release/obj.target/grpc/deps/grpc/src/core/lib/avl/avl.o] Error 1
make: Leaving directory '/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/westj/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.7.3-arch1-1
gyp ERR! command "/home/westj/.nvm/versions/node/v12.16.1/bin/node" "/home/westj/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc"
gyp ERR! cwd /home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/westj/.nvm/versions/node/v12.16.1/bin/node /home/westj/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.7.3-arch1-1
node-pre-gyp ERR! command "/home/westj/.nvm/versions/node/v12.16.1/bin/node" "/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc
node-pre-gyp ERR! node -v v12.16.1
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/westj/.nvm/versions/node/v12.16.1/bin/node /home/westj/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc' (1)
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.oinstall script
../deps/grpc/src/core/lib/channel/channel_args.cc:24:10: fatal error: grpc/compression.h: No such file or directory
   24 | #include <grpc/compression.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [grpc.target.mk:407: Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o] Error 1
make: Leaving directory '/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/westj/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.7.3-arch1-1
gyp ERR! command "/home/westj/.nvm/versions/node/v12.16.1/bin/node" "/home/westj/.nvm/versions/node/v12.16.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc"
gyp ERR! cwd /home/westj/Documents/fillyradionuxt/node_modules/nuxt-firebase/node_modules/grpc
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN eslint-config-prettier@6.11.0 requires a peer of eslint@>=3.14.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.1.4 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @grpc/grpc-js@1.1.1 requires a peer of google-auth-library@5.x || 6.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.10.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/westj/.npm/_logs/2020-06-22T17_28_06_501Z-debug.log
```

**Comment by ThisIsSet-L** [comment]
False alarm, I can't read
