### ISSUE TITLE
Calling messaging.getToken() throws DOMException

### ISSUE THREAD

**Issue by snorreks** [nuxt-community/firebase-module#387]
### Version
@nuxtjs/firebase: 7.1.0
firebase: 8.0.2
nuxt: 2.14.7

### Reproduction Link

```typescript
if (
!('Notification' in window) ||
!navigator.serviceWorker ||
!('PushManager' in window) ||
(await Notification.requestPermission()) !== 'granted'
) {
   return;
}

const currentToken = await this.app.$fire.messaging.getToken(); // <- throws DOMException error
```

### Steps to reproduce

My nuxt config:
```javascript
  modern: true,
  firebase: {
    lazy: false,
    onFirebaseHosting: false,
    config: {
      development: {
        ....
        fcmPublicVapidKey:
          'BByfCgJXUoNb2HC5g-BZIZxAAG5r03RIjmVDV8ubCxu7XIqmkWKuRqmU4-yTMxEoNYEB8VHmqoawipFE5XYK0yg'
      }
    },
    services: {
      messaging: {
        createServiceWorker: true,
        fcmPublicVapidKey: '<publicVapidKey>'
      },
      firestore: true,
      functions: true,
      storage: true,
      auth: {
        initialize: {
          onAuthStateChangedAction: 'auth/onAuthStateChanged'
        },
        ssr: true
      }
    }
  },
  pwa: {
    manifest: {
      ...
      gcm_sender_id: '1096610157142',
    },
    workbox: {
      importScripts: ['/firebase-auth-sw.js'],
      dev: !isProductionMode
    }
```
I get what I believe to be the encoded fcmPublicVapidKey from here:
![image](https://user-images.githubusercontent.com/36089469/99242947-33da7d00-2800-11eb-8ab3-c2be3bfc1212.png)

I get the same error when I have ssr: true or false. And when i have modern: true or false.
When I googled the error people said to add the polyfill: https://github.com/davidchambers/Base64.js, but the browsers I have tested on already has window.atob.

### What is Expected?

Get the fcm token.

### What is actually happening?

It throws error:

```console
actions.ts:62 initialize DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at base64ToArray (http://localhost:3000/_nuxt/vendors/firebase-messaging.modern.js:1499:19)
    at http://localhost:3000/_nuxt/vendors/firebase-messaging.modern.js:2137:51
    at step (http://localhost:3000/_nuxt/vendors/firebase-app/firebase-auth/firebase-firestore/firebase-functions/firebase-messaging/firebase-storage.modern.js:3287:23)
    at Object.next (http://localhost:3000/_nuxt/vendors/firebase-app/firebase-auth/firebase-firestore/firebase-functions/firebase-messaging/firebase-storage.modern.js:3268:53)
    at fulfilled (http://localhost:3000/_nuxt/vendors/firebase-app/firebase-auth/firebase-firestore/firebase-functions/firebase-messaging/firebase-storage.modern.js:3258:58)
```

Points to this function in firebase-messaging.modern.js:

```javascript
function base64ToArray(base64String) {
    var padding = '='.repeat((4 - (base64String.length % 4)) % 4);
    var base64 = (base64String + padding)
        .replace(/\-/g, '+')
        .replace(/_/g, '/');
    var rawData = atob(base64); //<-- points to this line
    var outputArray = new Uint8Array(rawData.length);
    for (var i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
}
```

**Comment by snorreks** [comment]
When I add the vapidKey directly in the getToken() method:
```typescript
const currentToken = await this.app.$fire.messaging.getToken({
vapidKey:
    'BByfCgJXUoNb2HC5g-BZIZxAAG5r03RIjmVDV8ubCxu7XIqmkWKuRqmU4-yTMxEoNYEB8VHmqoawipFE5XYK0yg'
});
```
I get this error:
```console
DOMException: Registration failed - push service error
(anonymous) @ actions.ts:64
asyncGeneratorStep @ asyncToGenerator.js:3
_throw @ asyncToGenerator.js:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
initialize @ actions.ts:7
wrappedActionHandler @ vuex.esm.js:847
dispatch @ vuex.esm.js:512
boundDispatch @ vuex.esm.js:402
accessor.<computed> @ index.es.js:53
mounted @ default.vue?75e0:44
invokeWithErrorHandling @ vue.runtime.esm.js:1854
callHook @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
invokeInsertHook @ vue.runtime.esm.js:6346
patch @ vue.runtime.esm.js:6494
Vue._update @ vue.runtime.esm.js:3945
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4479
Watcher @ vue.runtime.esm.js:4468
mountComponent @ vue.runtime.esm.js:4073
push../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount @ vue.runtime.esm.js:8415
mount @ client.js:732
(anonymous) @ client.js:776
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
_mountApp @ app.modern.js:1315
mountApp @ app.modern.js:1220
Promise.then (async)
(anonymous) @ client.js:109
./.nuxt/client.js @ app.modern.js:1317
__webpack_require__ @ bootstrap:853
fn @ bootstrap:150
0 @ app.modern.js:11281
__webpack_require__ @ bootstrap:853
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ app.modern.js:1
```

**Comment by lupas** [comment]
Hey @snorreks 

What browser & version are you testing this with? Did you try with e.g. the current version of Chrome? Does the error still appear?

If so: Could you check out how we do it in the [demo app](https://github.com/lupas/nuxt-firebase-demo/blob/master/components/examples/Messaging.vue) and see if if you do it similarly the same error appears?

Where exactly is the code you pasted under Reproduction Link? In a vue component?

br, Pascal

**Comment by snorreks** [comment]
It was only a brave error, have now tested on chrome, edge and firefox and they are all working 👍
