### ISSUE TITLE
Firestore rules request.auth is always null

### ISSUE THREAD

**Issue by vlourme** [nuxt-community/firebase-module#507]
Hello, I'm developing an app using Nuxt and this Firebase module, since yesterday, the emulator returns a weird bug causing every rules to deny operation. The `request.auth` is always null. I made some dependencies update yesterday and this is certainly the cause but I couldn't identify the package causing the bug. So I think this is from @nuxt/firebase.

### Version
@nuxtjs/firebase 7.5.0: 
firebase: 9.7.0 
nuxt: 2.15.3 

### Reproduction Link
N/A

### Steps to reproduce
The JS code triggering the issue: 
```js
await this.$fire.firestore
        .collection('users')
        .doc(rootState.auth.auth?.uid)
        .update({
          ...rootState.auth.user,
          team: id || null,
        } as User)
```

And the concerned firestore rule:
```
rules_version = '1';

service cloud.firestore {
  match /databases/{database}/documents {
  	// Users
  	match /users/{userId} {
         // Users are visible to anyone
         // Note: this is needed for team member searching
         allow read, create: if true

        // Allow only user to edit his own profile
    	allow update, delete: if debug(request.auth.uid) == debug(userId);
    }

    ... (other rules after)
}
```

### What is Expected?
The `update` operation should be accepted.

### What is actually happening?
At the beginning, I was sure this was due to `firebase-tools`, so I started writing my issue until I saw the `Invalid $httpHeaders`, then I thought @nuxt/firebase could be the cause.

Also, the JWT seems correct as you can see here: 
<img width="1170" alt="Capture d’écran 2021-04-02 à 10 43 04" src="https://user-images.githubusercontent.com/58728578/113399291-45cc4f00-93a0-11eb-9a9d-6db3be9f2dfe.png">

The `user_id` we can see here, correspond to the firestore document I'm trying to update and also is correct in the auth.
<img width="1253" alt="Capture d’écran 2021-04-02 à 10 45 26" src="https://user-images.githubusercontent.com/58728578/113399467-904dcb80-93a0-11eb-9fb9-28a255a68f00.png">
<img width="1255" alt="Capture d’écran 2021-04-02 à 10 45 46" src="https://user-images.githubusercontent.com/58728578/113399502-9a6fca00-93a0-11eb-8066-eb2d8a523f87.png">

```
Apr 02, 2021 10:35:51 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Apr 02, 2021 10:35:51 AM com.google.net.webchannel.server.common.CorsFilter populateCustomHeaders
WARNING: Invalid $httpHeaders: X-Goog-Api-Client:gl-js/ fire/8.3.2
X-Firebase-GMPID:1:457758151352:web:d22eb03c9eee56b64c5a4d
Content-Type:text/plain
Authorization:Bearer eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJlbWFpbCI6InZpY3Rvci5sb3VybWVAaWNsb3VkLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiYXV0aF90aW1lIjoxNjE3MzUyNTQ5LCJ1c2VyX2lkIjoidVplU2NnQmRpTGhUZXU2SjZCZzRENTZNRnlMUCIsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidmljdG9yLmxvdXJtZUBpY2xvdWQuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiaWF0IjoxNjE3MzUyNTQ5LCJleHAiOjE2MTczNTYxNDksImF1ZCI6Imludm9pY2VraXQwMSIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9pbnZvaWNla2l0MDEiLCJzdWIiOiJ1WmVTY2dCZGlMaFRldTZKNkJnNEQ1Nk1GeUxQIn0.

Apr 02, 2021 10:35:51 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
Apr 02, 2021 10:35:51 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected non-HTTP/2 connection.
string_value: "uZeScgBdiLhTeu6J6Bg4D56MFyLP"

Apr 02, 2021 10:35:51 AM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: 
Null value error. for 'update' @ L12
com.google.cloud.datastore.core.exception.DatastoreException: 
Null value error. for 'update' @ L12
	at com.google.cloud.datastore.core.exception.DatastoreException$Builder.build(DatastoreException.java:111)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.verboseError(EmulatorRulesAuthorizer.java:288)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.withVerboseErrors(EmulatorRulesAuthorizer.java:265)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.checkCommit(EmulatorRulesAuthorizer.java:117)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.commitHelper(CloudFirestoreV1.java:817)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.internalCommit(CloudFirestoreV1.java:731)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.internalCommit(CloudFirestoreV1.java:715)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1.write(CloudFirestoreV1.java:704)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.handleRequest(CloudFirestoreV1WriteStream.java:208)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.write(CloudFirestoreV1WriteStream.java:136)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.onNext(CloudFirestoreV1WriteStream.java:92)
	at com.google.cloud.datastore.emulator.impl.CloudFirestoreV1WriteStream.onNext(CloudFirestoreV1WriteStream.java:25)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.onMessage(FirestoreV1WebChannelAdapter.java:141)
	at com.google.cloud.datastore.emulator.firestore.webchannel.FirestoreV1WebChannelAdapter$FirestoreWriteHandler.onMessage(FirestoreV1WebChannelAdapter.java:111)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.onMessage(ChannelInternalImpl.java:485)
	at com.google.net.webchannel.server.v8.ForwardChannel.deliverMessage(ForwardChannel.java:114)
	at com.google.net.webchannel.server.v8.ForwardChannel.processPendingRequest(ForwardChannel.java:93)
	at com.google.net.webchannel.server.v8.ForwardChannel.consume(ForwardChannel.java:67)
	at com.google.net.webchannel.server.v8.ForwardChannel.add(ForwardChannel.java:60)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.handleRequestParams(ChannelInternalImpl.java:260)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.processSessionRequest(ChannelInternalImpl.java:317)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.handle(ChannelInternalImpl.java:142)
	at com.google.net.webchannel.server.v8.ChannelInternalImpl.consume(ChannelInternalImpl.java:78)
	at com.google.net.webchannel.server.common.ChannelProcessor.run(ChannelProcessor.java:80)
Caused by: com.google.firebase.rules.runtime.common.EvaluationException: Error: security.rules line [12], column [37]. Null value error.
	at com.google.firebase.rules.runtime.impl.DefaultEvaluator$TransformEvaluationException.apply(DefaultEvaluator.java:292)
	at com.google.firebase.rules.runtime.impl.DefaultEvaluator$TransformEvaluationException.apply(DefaultEvaluator.java:277)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:192)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:179)
	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:124)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1219)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:727)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.addListener(FluentFuture.java:117)
	at com.google.common.util.concurrent.AbstractCatchingFuture.create(AbstractCatchingFuture.java:51)
	at com.google.common.util.concurrent.Futures.catchingAsync(Futures.java:401)
	at com.google.firebase.rules.runtime.impl.DefaultEvaluator.evaluate(DefaultEvaluator.java:193)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRuleClient$EmulatorRuleEvaluator.evaluate(EmulatorRuleClient.java:91)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRuleClient$EmulatorRuleEvaluator.evaluate(EmulatorRuleClient.java:81)
	at com.google.cloud.datastore.core.auth.rules.SinglePhaseRulesAuthorizer.evaluate(SinglePhaseRulesAuthorizer.java:475)
	at com.google.cloud.datastore.core.auth.rules.SinglePhaseRulesAuthorizer.access$200(SinglePhaseRulesAuthorizer.java:80)
	at com.google.cloud.datastore.core.auth.rules.SinglePhaseRulesAuthorizer$CommitAuthorizerImpl.checkAccess(SinglePhaseRulesAuthorizer.java:702)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.lambda$checkCommit$0(EmulatorRulesAuthorizer.java:125)
	at com.google.cloud.datastore.emulator.impl.rules.EmulatorRulesAuthorizer.withVerboseErrors(EmulatorRulesAuthorizer.java:260)
	... 21 more
```

**Comment by vlourme** [comment]
I fixed it by resetting my `firebase.json` file to defaults (only emulators config is kept).
