### ISSUE TITLE
Cannot find module '.nuxt/nuxt-fire/firebaseServerAuth.js'

### ISSUE THREAD

**Issue by mtltechtemp** [nuxt-community/firebase-module#87]
Hello, i'm having issue with `nuxt-ts` when running `nuxt-ts build`.
It works fine in dev but fail when i build.

Stack:
```
  Error: Cannot find module '.nuxt/nuxt-fire/firebaseServerAuth.js'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-command.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:569:31)
  at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:727:66)
  at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:680:12)
  at Server.ready (node_modules/@nuxt/server/dist/server.js:610:5)
  at Nuxt._init (node_modules/@nuxt/core/dist/core.js:655:7)
```

Config:
```js
  /*
   ** nuxt-fire module configuration
   */
  fire: {
    config: {
      apiKey: process.env.apiKey,
      authDomain: process.env.authDomain,
      databaseURL: process.env.databaseURL,
      projectId: process.env.projectId,
      storageBucket: process.env.storageBucket,
      messagingSenderId: process.env.messagingSenderId,
      appId: process.env.appId,
      measurementId: process.env.measurementId
    },
    services: {
      auth: {
        initialize: {
          onSuccessAction: "User/handleSuccessfulAuthentication",
          ssr: true
        }
      },
      firestore: true,
      functions: true,
      performance: true,
      analytics: true
    }
  }
```

What did i missed?

**Comment by mtltechtemp** [comment]
cc @lupas

**Comment by josephfh** [comment]
Same issue here. This is what I get from the ```nuxt-fire-demo``` project when I run ```yarn generate```:

```
Cannot find module '/home/user/code/temp/nuxt-fire-demo/.nuxt/nuxt-fire/firebaseServerAuth.js'
Require stack:
- /home/user/code/temp/nuxt-fire-demo/node_modules/@nuxt/core/dist/core.js
- /home/user/code/temp/nuxt-fire-demo/node_modules/@nuxt/cli/dist/cli-command.js
- /home/user/code/temp/nuxt-fire-demo/node_modules/@nuxt/cli/dist/cli.js
- /home/user/code/temp/nuxt-fire-demo/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module '.nuxt/nuxt-fire/firebaseServerAuth.js'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-command.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:569:31)
  at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:727:66)
  at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:680:12)
```

**Comment by Space17i** [comment]
Same issue:

```
ERROR  Cannot find module '/var/task/.nuxt/nuxt-fire/firebaseServerAuth.js'
Require stack:
- /var/task/node_modules/@nuxt/core/dist/core.js
- /var/task/now__launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
  Error: Cannot find module '.nuxt/nuxt-fire/firebaseServerAuth.js'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - now__launcher.js
  - /var/runtime/UserFunction.js
  - /var/runtime/index.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:569:31)
  at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:727:66)
  at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:680:12)
  at async Server.ready (node_modules/@nuxt/server/dist/server.js:610:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:655:7)
 FATAL  Cannot find module '/var/task/.nuxt/nuxt-fire/firebaseServerAuth.js'
Require stack:
- /var/task/node_modules/@nuxt/core/dist/core.js
- /var/task/now__launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
  Error: Cannot find module '.nuxt/nuxt-fire/firebaseServerAuth.js'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - now__launcher.js
  - /var/runtime/UserFunction.js
  - /var/runtime/index.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:569:31)
  at Server.useMiddleware (node_modules/@nuxt/server/dist/server.js:727:66)
  at Server.setupMiddleware (node_modules/@nuxt/server/dist/server.js:680:12)
  at async Server.ready (node_modules/@nuxt/server/dist/server.js:610:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:655:7)
2020-02-02T11:21:57.808Z	2947eb47-0938-480c-941f-686c76739ccc	ERROR	λ Error while initializing nuxt: /var/task/node_modules/@nuxt/core/dist/core.js:1
Error: Cannot find module '/var/task/.nuxt/nuxt-fire/firebaseServerAuth.js'
Require stack:
- /var/task/node_modules/@nuxt/core/dist/core.js
- /var/task/now__launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Resolver.requireModule (/var/task/node_modules/@nuxt/core/dist/core.js:569:31)
    at Server.useMiddleware (/var/task/node_modules/@nuxt/server/dist/server.js:727:66)
    at Server.setupMiddleware (/var/task/node_modules/@nuxt/server/dist/server.js:680:12)
    at async Server.ready (/var/task/node_modules/@nuxt/server/dist/server.js:610:5)
    at async Nuxt._init (/var/task/node_modules/@nuxt/core/dist/core.js:655:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/@nuxt/core/dist/core.js',
    '/var/task/now__launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
```

**Comment by Space17i** [comment]
Seems that it's happens because deploying not on firebase hosting, and firebase-admin don't have access to GOOGLE_APPLICATION_CREDENTIALS variable. Here might be two solutions: first is to create this variable or second pass **admincredentials.json** at firebase-admin initialization step.

**Comment by lupas** [comment]
Sorry guys I'm still travelling for some more weeks and barely have time, I'll look into it as soon as I can.

It shouldn't have anything to do with the credentials.

`SSR: true` creates the serviceWorker file `.nuxt/nuxt-fire/firebaseServerAuth.js`. Can you check if that file gets generated after you run `nuxt build`? Not sure why TypeScript is complaining.

Could you let me also know if you're in `spa`oder `universal` mode?

As said I will look into it as soon as I can.

**Comment by Space17i** [comment]
Thank you for answer!
Yes, firebaseServerAuth.js file is generated, but forgot to tell, that I'm using **@nuxtjs/now-builder** for deploying on zeit.co winth default now.json configuration:

{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {}
    }
  ]
}

**Comment by Space17i** [comment]
Thank you for answer!
Yes, firebaseServerAuth.js file is generated, but forgot to tell that I'm using **@nuxtjs/now-builder** for deploying on zeit.co with default now.json configuration:

```
{
  "version": 2,
  "builds": [
    {
      "src": "nuxt.config.js",
      "use": "@nuxtjs/now-builder",
      "config": {}
    }
  ]
}
```

**Comment by smakman** [comment]
I'm having the same issue when deploying to Firebase hosting:

```
/srv/node_modules/@nuxt/core/dist/core.js:1
Error: Cannot find module '/srv/.nuxt/nuxt-fire/firebaseServerAuth.js'
Require stack:
- /srv/node_modules/@nuxt/core/dist/core.js
- /srv/node_modules/nuxt-start/dist/nuxt-start.js
- /srv/index.js
- /worker/worker.js
    at Resolver.requireModule (/srv/node_modules/@nuxt/core/dist/core.js:569:31)
    at Server.useMiddleware (/srv/node_modules/@nuxt/server/dist/server.js:727:66)
    at Server.setupMiddleware (/srv/node_modules/@nuxt/server/dist/server.js:680:12)
    at <anonymous>
```
In dev it works fine and firebaseServerAuth.js is being generated when running `nuxt build`.

**Comment by smakman** [comment]
I had to make sure the `.nuxt/nuxt-fire` folder got deployed as well, instead of only the `.nuxt/dist` folder. Seems to be working now.

**Comment by lupas** [comment]
Hey guys

Had a look at it and made some observations:
1) Running `nuxt generate` on a "sober" project (never built, no `/.nuxt` folder) results in:
```js
Cannot find module 'somePath/.nuxt/nuxt-fire/firebaseServerAuth.js'
```
2) Problem appears when `services.auth.initialize.ssr === true`
3)  Not specific to Typescript, throws error with `nuxt-ts generate` as well as `nuxt generate`
4) Running `nuxt` first and only after that  `nuxt generate` works (because `/.nuxt` folder and the file gets generated with `nuxt`)
  4.1. Nevertheless, the ___first time___ running `nuxt` throwed the error too, but succeeded anyway
5) In some cases `nuxt build` throwed the same error, in other cases `nuxt build` worked just fine

### Background

In nuxt-fire we do the following:
```js
if (auth.initialize.ssr) {
  // Add serverMiddleware
  const fileName = 'nuxt-fire/firebaseServerAuth.js'
  this.addTemplate({
    src: path.resolve(__dirname, 'serverMiddleware/firebaseServerAuth.js'),
    fileName: fileName,
    options,
    ssr: true
  })

  this.addServerMiddleware(path.join(this.options.buildDir, fileName))

```

First, we generate and add the `firebaseServerAuth.js` template to the `.nuxt/nuxt-fire` folder, and then we load this as a serverMiddleware.

The error happens with the line:
```js
this.addServerMiddleware(path.join(this.options.buildDir, fileName))
```
Without that, the error disappears.

### Solution
not sure yet, trying to figure that out

**Comment by standerpm** [comment]
Hi guys, any solution yet? Im also getting:  Error: Cannot find module 'D:\\test\\.nuxt\\firebase-module\\firebaseServerAuth.js'

**Comment by lupas** [comment]
Should be fixed with v5.
